module.exports.configurables = {
    // Slack Bot Token
    oAuth: '',
    botToken: '',
    clientSecret: '',
    signingSecret: '',
    // Espn Info
    leagueId: 0,
    espnS2: '',
    SWID: '{}',
    // Score weights
    scoreWeighting: {
        passingYards: 0.04,
        passingTouchdowns: 4,
        passing2PtConversions: 2,
        passingInterceptions: -2,
        rushingYards: 0.1,
        rushingTouchdowns: 6,
        rushing2PtConversions: 2,
        receivingYards: 0.1,
        receivingTouchdowns: 6,
        receiving2PtConversions: 2,
        receivingReceptions: 1,
        lostFumbles: -2,
        madeFieldGoalsFrom0To39: 3,
        madeFieldGoalsFrom40To49: 4,
        missedFieldGoals: -2.5,
        madeExtraPoints: 1,
        defensive0PointsAllowed: 10,
        defensive1To6PointsAllowed: 7,
        defensive7To13PointsAllowed: 4,
        defensive14To17PointsAllowed: 1,
        defensive22To27PointsAllowed: -2,
        defensive28To34PointsAllowed: -4,
        defensive35To45PointsAllowed: -7,
        defensiveBlockedKickForTouchdowns: 6,
        defensiveInterceptions: 2,
        defensiveFumbles: 2,
        defensiveBlockedKicks: 2,
        defensiveSafeties: 2,
        defensiveSacks: 1,
        kickoffReturnTouchdown: 6,
        puntReturnTouchdown: 6,
        fumbleReturnTouchdown: 6,
        interceptionReturnTouchdown: 6,
    }
};